#!/usr/bin/env python3

"""
Autor: Rafael Costa Biasi [https://rafaelbiasi.com.br/] [https://github.com/rafaelbiasi]
Versão: 1.0.4
"""

import os
import subprocess
import argparse
import json
import time
import base64
import getpass
from cryptography.fernet import Fernet
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.service import Service as ChromeService
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.chrome import ChromeDriverManager

# Obtém o diretório onde o script está localizado
SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))
CONFIG_FILE = os.path.join(SCRIPT_DIR, 'vpn-config.json')
KEY_FILE = os.path.join(SCRIPT_DIR, 'secret.key')

def generate_key():
    key = Fernet.generate_key()
    with open(KEY_FILE, 'wb') as key_file:
        key_file.write(key)
    return key

def load_key():
    if os.path.exists(KEY_FILE):
        return open(KEY_FILE, 'rb').read()
    else:
        return generate_key()

def encrypt_password(password, key):
    f = Fernet(key)
    return f.encrypt(password.encode())

def decrypt_password(encrypted_password, key):
    f = Fernet(key)
    return f.decrypt(encrypted_password).decode()

def load_config():
    print('Carregando configuração.')
    with open(CONFIG_FILE, 'r') as f:
        return json.load(f)

def save_config(config):
    print('Salvando configuração.')
    with open(CONFIG_FILE, 'w') as f:
        json.dump(config, f, indent=4)

def install_packages():
    print('Instalando dependências.')
    subprocess.run(['sudo', 'apt', 'update'], check=True)
    subprocess.run(['sudo', 'apt', 'install', '-y', 'openconnect', 'openssl'], check=True)
    subprocess.run(['pip3', 'install', 'selenium', 'webdriver_manager', 'cryptography'], check=True)
    subprocess.run(['sudo', 'pip3', 'install', 'vpn-slice[dnspython,setproctitle]'], check=True)

def configure_driver(args):
    print('Configurando web driver.')
    chrome_options = webdriver.ChromeOptions()
    if not args.manual and not args.browser:
        chrome_options.add_argument('--headless')
        chrome_options.add_argument('--disable-gpu')
    chrome_options.add_argument('--window-size=720,540')
    chrome_options.add_argument('--ignore-certificate-errors')
    chrome_options.add_argument('--ignore-ssl-errors')
    return webdriver.Chrome(service=ChromeService(ChromeDriverManager().install()), options=chrome_options)

def wait_for_page_load(driver, timeout=30):
    print('Esperando página carregar.')
    WebDriverWait(driver, timeout).until(
        lambda d: d.execute_script('return document.readyState') == 'complete'
    )
    time.sleep(1)

def automate_login(driver, host, username, password):
    print('Login automático.')
    driver.get(host)
    wait_for_page_load(driver)

    email_field = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.NAME, "loginfmt"))
    )
    email_field.send_keys(username)

    next_button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.ID, "idSIButton9"))
    )
    next_button.click()
    wait_for_page_load(driver)

    password_field = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.NAME, "passwd"))
    )
    password_field.send_keys(password)

    sign_in_button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.ID, "idSIButton9"))
    )
    sign_in_button.click()
    wait_for_page_load(driver)

    dont_show_checkbox = WebDriverWait(driver, 10).until(
        EC.presence_of_element_located((By.ID, "KmsiCheckboxField"))
    )
    dont_show_checkbox.click()

    yes_button = WebDriverWait(driver, 10).until(
        EC.element_to_be_clickable((By.ID, "idSIButton9"))
    )
    yes_button.click()
    wait_for_page_load(driver)

    cookie = driver.get_cookie("SVPNCOOKIE")['value']
    driver.quit()
    return cookie

def manual_login(driver, host):
    print('Login manual.')
    driver.get(host)
    print("Por favor, faça o login manualmente...")
    while not driver.get_cookie("SVPNCOOKIE"):
        time.sleep(1)
    cookie = driver.get_cookie("SVPNCOOKIE")['value']
    driver.quit()
    return cookie

def connect_vpn(cookie, host, lan_enabled, server_cert, vpn_slice):
    print('Conectando na vpn.')
    command = ['sudo', 'openconnect', '--protocol=fortinet', host, '--servercert', server_cert, f'--cookie=SVPNCOOKIE={cookie}']
    if lan_enabled:
        command.extend(['-s', f'vpn-slice {vpn_slice}'])
    subprocess.run(command, check=True)

def keep_sudo_alive():
    print('Mantendo o sudo vivo.')
    while True:
        subprocess.run(['sudo', '-v'])
        time.sleep(60)

def check_for_updates():
    print('Verificando atualizações.')
    result = subprocess.run(['git', 'fetch'], capture_output=True, text=True, cwd=SCRIPT_DIR)
    if result.returncode != 0:
        raise Exception("Erro ao verificar atualizações.")
    result = subprocess.run(['git', 'status'], capture_output=True, text=True, cwd=SCRIPT_DIR)
    if 'Your branch is up to date' in result.stdout:
        print('Nenhuma atualização disponível.')
        return False
    else:
        print('Atualizações disponíveis.')
        return True

def upgrade_script():
    print('Atualizando script.')
    result = subprocess.run(['git', 'pull'], capture_output=True, text=True, cwd=SCRIPT_DIR)
    if result.returncode != 0:
        raise Exception("Erro ao atualizar script.")
    print('Script atualizado com sucesso.')

def parse_arguments():
    print('Configurando argumentos.')
    parser = argparse.ArgumentParser(description="Script unificado para conexão VPN.")
    parser.add_argument('--install', action='store_true', help='Instala os pacotes necessários.')
    parser.add_argument('--off', action='store_true', help='Conecta ao VPN com LAN desabilitada.')
    parser.add_argument('--manual', action='store_true', help='Usa a execução manual do script de cookies.')
    parser.add_argument('--browser', action='store_true', help='Mostra a execução do login SSO no navegador.')
    parser.add_argument('--host', type=int, choices=[1, 2], default=1, help='Define o host VPN para a conexão.')
    parser.add_argument('--setup', action='store_true', help='Configura o arquivo vpn-config.json.')
    parser.add_argument('--plain', action='store_true', help='Usa a senha em texto claro (não recomendável).')
    parser.add_argument('--update', action='store_true', help='Verifica se há atualização do script.')
    parser.add_argument('--upgrade', action='store_true', help='Atualiza o script.')
    return parser.parse_args()

def setup_config():
    config = load_config()
    for key, value in config.items():
        if key == 'encrypted-password' or key == 'password':
            continue
        change = input(f'Deseja mudar a configuração de "{key}" (atual: {value})? (y/N): ').strip().lower()
        if change == 'y':
            new_value = input(f'Insira o novo valor para "{key}": ').strip()
            config[key] = new_value

    save_config(config)

    change_password = input('Deseja mudar a senha criptografada? (y/N): ').strip().lower()
    if change_password == 'y':
        sudo_password = getpass.getpass("Digite a senha do sudo: ")
        plain_password = getpass.getpass("Digite a nova senha que deseja criptografar: ")
        key = load_key()
        encrypted_password = encrypt_password(plain_password, key)
        config['encrypted-password'] = encrypted_password.decode()
        save_config(config)
        print("Nova senha criptografada salva no arquivo de configuração.")

def main():
    print('Iniciando vpn.')
    args = parse_arguments()
    config = load_config()
    key = load_key()

    if args.install:
        install_packages()
        return

    if args.setup:
        setup_config()
        return

    if args.update:
        if check_for_updates():
            print("Há atualizações disponíveis. Use o parâmetro --upgrade para atualizar o script.")
        else:
            print("O script está atualizado.")
        return

    if args.upgrade:
        upgrade_script()
        return

    if args.plain:
        print("Aviso: Usar a senha em texto claro não é recomendável.")
        password = config['password']
    else:
        sudo_password = getpass.getpass("Digite a senha do sudo: ")
        password = decrypt_password(config['encrypted-password'].encode(), key)
        command = ['echo', '-n', sudo_password, '|', 'sudo', '-S', 'true', '2>/dev/null']
        subprocess.run(command, shell=True, capture_output=False, text=True)

    host = config['host_mapping'][str(args.host)]
    username = config['username']
    server_cert = config['server_cert']
    vpn_slice = config['vpn_slice']
    lan_enabled = not args.off

    # Verificar atualizações no início da execução do script
    if check_for_updates():
        print("Há atualizações disponíveis. Por favor, atualize o script para a versão mais recente.")
        input("Pressione Enter para continuar...")

    driver = configure_driver(args)
    hostHttps = f"https://{host}/"

    print('Host selecionado: ' + host)

    if args.manual:
        cookie = manual_login(driver, hostHttps)
    else:
        cookie = automate_login(driver, hostHttps, username, password)

    connect_vpn(cookie, host, lan_enabled, server_cert, vpn_slice)
    keep_sudo_alive()

if __name__ == "__main__":
    main()

"""
?v=PsCJWAkA8S4
data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD/2wCEAAkGBxASEBAQEBAQDxAQD
w8QDxAQDxAQEBAPFhUXFhUVFRcYHSggGBolGxUVITEiJSkrLi4uFx8zODMtNygtLisBCgoKDg0OF
Q8PFS0dFR0tKy0tKysrKy0tKystKy0tKysrKystLS0tKy0tLS0tLSstLS0tLS0rLSstLS03LS0rL
f/AABEIASwAqAMBEQACEQEDEQH/xAAcAAABBQEBAQAAAAAAAAAAAAAAAQIDBAUGBwj/xABIEAACA
QMBBAUIBggEBQUBAAABAgMABBESBQYhMRMiQVFhBxRScYGRkqEWMkJTsdIXIzNicsHR0xVzk7IkQ
6Lh8GNkgqPCNP/EABoBAQEBAQEBAQAAAAAAAAAAAAABAgMEBQb/xAAzEQEAAQICCAQEBgMBAAAAA
AAAAQIRA5EEEhMhMVFS0QUUFjIVQXGhMzRhgbHBIkLwcv/aAAwDAQACEQMRAD8A66oCiigWgSgWg
SgKqDFAYoENAUS5DQNIoG0AaqkxUS5pFA0igY1Aw0Glio0MUC4qXBiiDFLqwdq73WUBKtJrcc0jG
sg9x7B76XFaDfqwZdRlZO9WifV8gc1Li3ab2WEhwtwgJOAJMx5+ICrdG2jAgEEEHkQQQaodVCEUD
cVEIRQNIqhKAqhKgaRQNNVDCKgYaDSxRsVAUDZZFVSzEBVBLE8AAOZNSR5JvPvfNPKwicxwKSqKp
I1j029fdWY3jml4k54nvrdggFAhUHlzpYX9l7SngOqGVo8HOAeofWvI1JHp27W+UNwAkumGflgnq
Oe9SfwPzqRI6itoSgaRRDSKgbiqDFAAUQ0igYRVDSKBhFQaNRoYoA0Hm/lL3iOrzOJsKADcEfaJG
QnqxxPsrMq88D8asCRXxnsqh0bd9AqHjigdpoEwcVFdruLvS6MLeZyyHhGXOdB9HJ7DSJSz07NaQ
GiGMKBMUsExVBRCEUEbCgaaBhFBoVGhUCPyPqoPnzaVyZZpZWOTJI7+88PliswKuKqlBoJI0J5UW
Fg2bcDnnUu3Zt2O787qCIyQe00u3ThzKzNuvOpAWJ2yOJAGM1JlZwpZ8WyZFlCMrKxPdyGedIZmi
Yex7OVhGqsclRjPacVtwlaqoaaBuKoMUCEUQ01A0iqGGoGmqNDFZaGKBkhwCT2Amg+dSc8eWeOO7
NSFAWgUJUVdsLR3PVHDvPAUmXSmm7p7G2VMasHxrEy6xFm/b7egTgWOB3AkUdNaIaVlvHbycAePj
wNG4qut3s0JUsxAGPrGpElXBpbNmV4kkQ5V1BB767Q+dVxWa0yaRQJiiEoAigaRQNIoGMKBhFBoV
hoYqiK7B0PgZOhsDvOOFB88xQklVAyeAA8ajUQ1V2BMRkGPxAbLVmaodtjKk9sVODzq3c9W0trZ0
bhB12X2KR+FYl2ohdNpIRnXkdnVGD7qjcwhljm0aiCwLBVCrjB7S3Ph7q3EMSdbWjBgcGPODqxwx
UahfuYrhzBGy5SVj0eMsJAPDs4ccVYouVS7uygvEWJSlsIh0aYUyawnI9mM4rpazyTva2KrJpFAl
RCYqhCKBCKBhoGGiGEUVoYrLQqhGHA0R4LZr+vPZxlHqODiudTvhTvbk0RjaIqABhetxy2R31zs9
kqW0oev3HjmtQ89cb2nYcFFJbp4NewKjh2HmP6VG7NlbWIjgPkTV1k1VTaVohADZBJzgjGR6udLr
qrOwnGpUI4I2pR3Ef8AakVbyqm8OuL5A7udd73eCrdNjcUYIRQNIoExQBokmmgjIqqaRUQ0igv1G
higMVB47vdszze/bAwkp6WP1NzHsYH3iszDpRO9dYrJGEckEA6D6J7D8q5vZFV4Yu03Ixk5IJBPe
e+rDlXJNn3vHBPqokVN2B+RqOsS39nbQKijpdhbd2myyiVXD8MMCeRqwxNdlbY+0pHm60mnODgDH
DPHFSyU13eq2n7NP4R+Fdo4PFie6UtVgUDcVQYoENAwigYRRDSKBhFVV81lRQFBxvlIswY4ZscY5
CpP7rD+oFSWqXIA5FcXppZW15AOr286sM1SzIpMEeutMw6XZ1zq4Z4ipLtTKbad4Y4ur9ZuAx2Dt
rKzLIghZx1kdvY1aY4rlgqtPBGqMp6ZVZuI4Z63PtoTuevX1/FCo1tjPBVHFj6hXWHkmbyZY7Ujl
4LkEdjCrZF6gQigKBuKIYRQg0iimmqhhqC/io0MVBn7c2tFaQtPKTpXAVVwXdzyVQe3+QJpI8o3j
8oU10jQCCOGMsCCS0kmAcjjwA91ZmJajcp2N4GUfMdxrEvRTLO2x9fNWGamcJMVphat7sg8KjUS1
7HaOWQtxweOazZuKnQy3vRjUo1dvhS7pEs//GS80DlApjkDeviD/KrHFzrm8NG8vXN3MZTlhIwAz
yQHqgeGMV3h5pbFrfO+NJCRpgnJCRjxbvNauzZ2dpOsiK6MrqwyGUgqe/BHjWRLiolxRSYoGsKMm
GqppqBjUF+o0ZNKqKzuyoiglmYhVUDtJPIVLjyHykbxw3UsSwOZIoVfJ0lVMhPEjPPgBx/rRXFMA
ezj31oT20ulsjlyYVmqm7VNVmpcRh148a5cHfjDEuYCh8K3EuUwiVqrJ6TYqTC3aEO1GAxnh3Vmz
WsVbws1LF3qDbsreW8M8b9FOY0DsRlZCAB1scjw5iusOU8XnEm0p4Zx0gIa3lIaFvqgg4PDtPPj4
1R6RsDbih1k1M1tdFQSckQT8B7AeAPcdJ4ZNVHaEUYJiosihBhFC5uKqGkVERsKNJNqbRit4mlmb
Si+0sexVHaT3Vm7Tx7eveaa9bDfq7dWykAOeXJpD9pvkOzvKI33Vz+gVQ7o6qIpo+0c6C7sybIKH
mOXqrlVG96MOq+5JPF2EVlqYUJ7H0fdViXOaVJ4WBwQa3G9iSBDVsl2/uvs+CSZRcTrAnDi2cN4a
uQ9tLF3u1jAiRokeNAUBcHII789taYlwXlU3Z1r59CuXjAFwo+1GOT+scj4Y7qES43c7ayIzWs/G
3n4dbkjEEZPgQcH19pAq0y09a3YuXaMxOdbQsUD6gS8YAwW/eH1Se0rntrnViRDcYM1NhT4Yq01x
LFWHNPEpFbczDUQ0iimGgYaDxbeTeGa7lLyHCjIjjB6sa9w7z3ntrNm2SDwzWgqmqH540ARQRcUY
H2ipMXWmbNvRkK2ODAEHvFcJeqJuRYONRbK+1I9DRqQOtHrHf8AWZf5V0oefE4saeLBz2GulnM62
mwcGg6HYm8l1akCGQ6OfRP1oj7Oz2YpYej7vb7W9z+qmCwSsCNLnMUg7QGP4H50ncWeeXWyIBez9
DloFkzEGGMHtx3qDnHfXKquPk60U3dhsO4eNeqSCRj2V55eql1eybnVHgkatWcnmfCkTbeTTrRaW
h669dFWtDwV0as2IRW3MyoGmqphFEfPDT+GajojW6I4FeFBZhdW4g+sVRJIOXhQSquaIZejqg934
VFbe58wkLWzDUCDJF/+gPx99ccSPnDcVWdhZ7sozDg3qzwrjrNbSWP5UtgC3Nrcp9VgLdx2AjU6E
ezpPlXXDlzmbuMdcivQjMmUqayLlpLqHiKov2xwwPaONSrgtPFuWEmc555rzS9UOm2enAVh0a6KV
IK8MEGitu3vVc5zg4457TXTDqs44tGtH6rWK9LxGMKIbQMYVSXzcVrLqckdBJ0OeI4HsIqwieOUj
Cv28m7DVE0ZwcUsiZuIIpZVfZF00MqyIQJIXDKDybHAg+BBIPgTWZhYe47u38VwiXER6rcGQ41RS
dqN4j58DXnqi0iHyq2evZVwQMmJ4Jh6hIqt/wBLNVp4jxS2ORivRCIbqKkilA+lqg2bds4NKuCxx
dXYbPxpbsOK8kvZTG5v2i4ajbWjfIxRJVby66LTzLSMEjQc3cngBViLszVZ1ijgM88DPrr1Q+fM3
khqobiqGkVB83VHQqZoJlNUT4DDBFBXkkKcDxHY3h41Rct5gw4UFG/GHBHMj8Kit7dDek2UwdgzQ
SYWdB/0yAdpHH1gnwrFdN1h7XtjRebNuBEwdbizlEbKchsoSpHtxXKN0kw+eYJuRHaARXaEWjhh2
H1VplmXcJHHxwaium3N2O82JGGIxyz9o+HhXPErtDvh4czveiQ24AC4ryvXELHmGnrd9ahmVRrwI
Tk4ArdmZlV2dt2K7keOIhZ7ZhLbO2MPgYcfwkFgfAk9gr0YUWje82JN3Z7NvUniWVOTZBGQSjqSr
occMhgR7K3MPPMLJFRk0iqphFJHzaTWXUh9eKCSJz21UXo4ZOH6tyP4Gx+FatPJicSiP9ozhK1o7
DBjfH8Df0q2nkm1o6ozhnJbyxyY6OUj/Lfl7qzqzyXa4fVGcLF9Zu2G6OThg/UblyPZTVnku1o6o
zhA9lJoI6OThxH6tuI91NWeSbWjqjOHZeSu/lWRrKU3MUbhnhZdSKrgEspyMYIyfWD31zronjZ2w
9JojdeJ/eHK7SsXSeZFR3RZZFRgjEMmo6TwHdirTE8nOrFov7ozgljDKNQ6OQEMSOo2CD7K3qzyZ
2tHVGcFntpGPGNzk8eo39Kas8iMWjqjOHcbtbc0hYpoTGAAqukbaR/EMcPXXCvBqnfZ6aNLw+GtG
cO0gjGQ3Zzz4Vx2dXJ6NtR1RmrbV2sMqgByzqikghck4ye4eNbpw6uTnXj4cf7RnCwm6kDpItw3S
tKjIcHSsYPan73jXopw93B5a9IpmeMZvOIvJ7tBZmjVU0BiouOmRUaP0sA6uXZj+tbiiWNrR1Rm9
Y3e2UlrbR26Nr0Alm5anYks2OziTw9VJiU14q4SvGoExUDGFUfNOKy6mlKAwaEPRN6d557G3sOhW
JulhOrpVdsaEixjSw9I19TGx6sKijV+cdn5LQ/D8LS8bH2kzGrPyt85n9J5Ob/Sdffd2vwS/wByu
HnsTlH37vo/ANG6qs47D9J1993a/BL/AHKeexOUffufANG6qs47D9J1993a/BL/AHKeexOUf9+58
A0bqqzjsP0nX33dr8Ev9ynnsTlH/fufANG6qs47D9J1993a/wCnL/cp57E5R9+58A0bqqzjsP0nX
33dr8Ev9ynnsTlH37nwDRuqrOOw/Sdffd2vwS/3KeexOUffufANG6qs47D9J1993a/BL/cp57E5R
9+58A0bqqzjsP0nX33dr8Ev9ynnsTlH37nwDRuqrOOw/Sbe/dWv+nL+enn8TlH37p6f0XnV9uw/S
be/dWv+nL/cp57E5R9+6+n9G6qs47E/SZe/dWv+nL+enn8TlH37p6f0XnVnHYfpMvfurX/Tl/PTz
+Jyj7919P6LzqzjsfF5UL5SGWO1BH/py/nrNemV1xq1RFv37umD4Lg4NcYmHXVFUfrHbg90sLjpI
o5CNJdAxGc4Jry0zeLvt6XgRgY9eFE3imbJq085rUR4Z5P44ZL+C3ntoLmO5cI3TCXVGFR2zGUdQ
CeGcg8hyrDrC1b7FS5sLi8CQ20rQPdJCkLpEkNs+mRYDJOXYvwJcIyjGnKkmiotj7rQywQSy3jwv
cxX8qItoJURLMky6m6VSSVBIAHMYJ7wTyo6eh2ZpLFeil0lgFYrphwWAJAOOzJ9Zr3aX7MP6dnwP
BvxtJ+sfzUytiboRPapeX1/Hs6CeV4bXVDJcPO6fXbSn1UBONR7fZnwvvspd178wG5W0uGtgrv06
wuYtCfWfVjGnx5cD3UFpNz71JLfzq0u7eGa4igMhtpGILsBhVx1mwThe0jAoLO09w76MW7xQzTJd
z3MVsohlWc9E7AdLGR1GZUZwMngrHsoH2O5UvQ3r3aXFrLbLZNHE0B1yJPciAsFOC2OtjHMigo7R
3VuVe5aCC6ltre5836Z7d4jrLBVVlP1WJZRjn1hyzQD7lbUGSdn3gwjuc28owqnDHlQUzu/eC288
NrOLX78xP0WOWdWMac8M8s8OdBt2e5jvsoX4S6llmuxb20UMGuMgFVLyNz4sSi4H1lx28ANm7i3O
bsXsNxZmDZ95eRa4ivSvBoyo1c164yR3igTfXce4srhkjhuZbYtBHDcNC2mWWSJH0KQME6mZRjnp
I5g0GXd7q7QicRy2dyjmJ5grQuCYkGXblyUEZ7s8aDOu7KWLo+ljePpYkmj1qV1xN9V1zzU4ODQV
6D6g3YuBJax4BGjVGQe9CRn28/bTD9sPV4tu03G+rUIrcvnmNQfN9jeyQypNC5jljbVG4CkqcEcm
BB4E8xWHVcg23epbdCkji2Eb2hPQRMBHKGZoOmKFsHLNo1cMZAGM0VWj2vcIiKsrKsMdzHENMeEj
uAROBkfaBPPl2YoQ2/KaP8Ah9l/5Mn+yCvdpfsw/p2fA8G/G0n6x/NTN2PvZbi0jsr+wF/FbyyS2
rLcvbSRdJgyIWVTqRiAew/LHhffaS+UVPNehazYz/4Sdk9MLxliFvjCP0OgjWOGePHHZmg3t7/KL
bxXtwLSHzgSXmzLia488Z4pltTHKqxJpxGSw0k5PI8OwBiReU3DxE2mY1Xa0cyi4ZXeK+mMrBHC5
jZDgauOcHlmgjvPKKjIYo7Jo4/NNnWsYa7MrKlpdG4BLGMaiwOnsxjPhQSzeUmNluQ1j0jTXrXkY
luEkjt3aRXJiBi1K+ldOQwB1ElTyoJIfKoyzrMbVmC7Tu9oaDdHGJoDCIs6OS6ic9vLAoKT+UIG0
6IWhFydlrskzm5Yw+arjrdBp/aYHPVjPHHZQVt2d/Gs47KNYBIbO9nustKQJFli6FkAC9UgFiGye
J5UF+48osXQC3gsnjiWx2lZr0t60z/8Y0bFyxjGdJjPV7dXMY4hIfKpJ09xOttxmuNmzojzl0i80
TSVA0DOvnkYx40Cx+UuNDGkViwttV888ct680sjXS6X0SlB0YGeWDnmeJzQZO8G8Vndxu7W7RyQW
llYbOiMrydHFGWLzSOAoZsYUDGOvnHCg5Cg+n917iE28aRtGWQfrEUjUrk5bUO8kk+2lHth6/FYn
zmN9WuRWnzkbCqPmvZoi6eETkrAZ4ROwyCIC69IRjj9XVXN2emSLa6OhuE2VFH/AIq8lpFBPCIJ4
hZ3Xmjz9HJwjaTowWbBOcNwqjmtpm2hutlSTxW0UqSRybUgtOjeBUS5BTqxlkDtCCWVT6PAE0Evl
kk1eZtrEmprtukX6smTEdQ8Dz9te7S/Zh/T+ofA8G/H0r/1/dTEi3KdtlwXqR3c093cPFbxQ25eI
Ih0kyNzyxzpwPsmvC++j2fuVcYvfPIri0a2sLi7iEkLJ0zRPGhA1DivX5jwoDfPci5srt4Y4LmWA
zrBbTGBv+IkKg6UwMM2SQAOeD3Ggxdr7Cu7UqLq2nt9ZYJ00TIH041aSRhsal5d9AbR2DeW8cctx
bTwRy/s3lidFbtwCRzxxx3caDo9ubgXEQ2fHBBeXFzdWfncyi2IjQHSdCHmWTUA+cYLJ6WKC1ut5
PDcKoujcWkp2hBaNE8Wh1SSF5Q5D4IPVHvoOcl3S2gJ1txZXXSyKzxIYJA7xg/WAI5cs91A1d1No
lmTzC71oqs6m2lBRWDFS2R1QQjcT6JoJr7dW5iso7t4bpQ5LNqs5lhigJVY3aZgFy7E4UZ4YOeIF
BgUBQFAUHdbQnaOZ2VirazgqSrDh2EVKPbD3eKfnMX6tfd3fm5t2AkZriEnrJIxLjxRjxB8DwrV3
z5h3Wzd/LGUHW5t2H2ZRwPqIyDVuzqvB81h0OTHdVDscKEOo8pv/wDPsv8AyZP9kFe7S/Zh/Ts+B
4N+NpP1j+alTd7f9rVNnILfWLGS+Zv15Xp0uV0lRhcxlRnDAniff4X31m98oURh83hs3jiXZ15s9
DJeGZwJ5o5ekJMYzjo8af3uBGMUFtvKu/nElwtoMvtOG/CvcF1VUgMDRfUHNSSG7OHA4oMDeveqK
6htIILaS3S0kupFM10bt3M7IxyWQcinjnPtIX99vKB/iELRi3MDSzx3E56SJ0LpGYwEAiVscc5Zm
IzjOKCSLyhqR0U1q7wNsq02dKiXbRSsYDkSpIE6uo80wcjgSaDQPlXHT9MLE4F3aXIU3ZY4gtzBo
LGPJznVqPz50FDZ3lG0QxQTWzzRrbbQtZ2F0ySyR3U6zZR9BKFSgHHUG8KBu3/KJ5xBcwRWz24ng
2dAG87aVlS0L/WJQF9WsZyeztzQSbxeUZLq2vIvM3jnv0sxcS+eM8StbspBjhKdUELy1cM+HEOAo
CgKAoOs23J+vlH7/wDIVmj2w93in5zG+v8AUM0Mc1p4UmugpMKgcjUEinsNUbG0rmS/jtLfKJLbL
KupzpWVToCYwDhgE4j2jtA642PNVFMTHBz8L8JvpOLGHXEbS0xE3477xG6eap9C7n0ofjf8tebaw
/RendK6qc57D6F3PpQ/G/5abWD07pXVTnPYfQu59KH43/LTawendK6qc57D6F3PpQ/G/wCWm1g9O
6V1U5z2H0LufSh+N/y02sHp3SuqnOew+hdz6UPxv+Wm1g9O6V1U5z2H0LufSh+N/wAtNrB6d0rqp
znsPoXc+nD8b/lptYPTuldVOc9h9C7n04fjf8tNrB6d0rqpznsPoXc+lD8b/lptYPTuldVOc9h9D
Ln04fjf8tNrB6d0rqpznsPoXc+lD8b/AJabWD07pXVTnPYfQu59KH43/LTawendK6qc57D6F3PpQ
/G/5abWD07pXVTnPY7br/8AETfx/wAhWqPbD5/if5zG+v8AUIdn2ckzhIl1OckDIHD21p4XY7L3c
hhAa5Rp5SQQiHEaD949tahHn7msKaBVEoNA4Mfd+NDhvhJ5y/3knxt/WpaOTrt8XrqznueLl8fXf
n6bePjVtHJNvi9dWc9zxO5AGt+BP225e+lo5G3xeuc57nx3DlVGt89vXb+tIiOSbfF66s57p1uG4
jW/D95v61bRyNvi9c5yOnfP13+JqWjkbfF65zlatRI3Jn4czqbhUm0RwdMOvGxKoiK5zls7ER0u7
bVqCSLMFDPkuyoWzp7B7653iY4PXixiYdv85zlpXcXSMIlLEm4RToBZlUkKSQO7Oa1h0w8dePiX9
85yfvRsgWzBUaQhw4yzD6yFc4x666TTHIpx8S3vnOVfcKXF62sllaB1wxyAdSEHjw5A++s2i3Bnb
YnXOcuR3k6WK6uI2Mi/rpHTrMAYmYshHHlgipEQbfF65zllecyfeSfG39aWjku3xeurOR53J94/x
t/Wlo5G3xeurOe5jSE8TxJ5k8TVc5mZm8zeW5utO6GSRCcqBw+yR258asI6Q7dcgaBnrAt3Y7aI8
9IrKlxVEbHjQOV6geDVD05Hx/GgdGaImtT2YJOTgAVqKZGlZbEvHYtHaTuCMfsn0+vOMU1ZF+PdS
9z11hh8ZbiFflqz8qas80XY9kui6JNq28SAk6Iekc5PM9VBk+2pVREt0YlVPtFoLCGVJjfXFxLGT
gmHCAEFTkl2OMMaWiIXa1VTvl0Nxs8xv0sZeVnkgmQwnKvF1WyHXPA6QcYOc1qmmzNU3lZ3omklK
FU6Hi8mC7Fv1oXhgY4DTn2mkylmZsbdqRyZpGJCggqYixJI4ftOr+NQdFtndqxuBGLlT0iJgTR9J
rClmIXC8CBk8++utOFrReGKq7Kdl5OdkgYK3dyWyQxuFi0jv0qo+ea1sJZ2jJ2p5MrVesk1zCmcs
00lsyKueWcL/OtRgU/OScSrk5q/2TsiHIW4nvGx/wAsqqA+sLx9hqVRhU/rJE1z8rHW+8QiiaGCz
jCNjJMQLHHDix4sfE5rhr8nVnxXspIwoQcjgc+f9axdWEcUBQQtQNoJFJqDYtZYF6JnTpdMp6SPL
KkkZU44jBHHFWBrjeGFf2Oz7RPF4+mP/wBhatayHHe+95I6QjuhjSL/AGgVNaSyncbaupP2lxK/r
cmpeSyTY1q808avHPLGS5k0iQnARiOI5ZYKM+NS7UUukhW2jJAsotQ+8SSRlP8A8ycHnS5qodpyr
NGIS0cI1pJ1IlyMBlxgEel8qXSzrt096be1tEtZekuRGZAjEKg6NiToKlyCBkj1AU1yVm+3n2dK2
prMsf8AMCf7RV15lm0o23ptRG0cdoiBhjIk64HDODpz2VdYs5672paayxg4k5Jaa6Y+wdIB8sU1p
jgtoVZ9vW32LbUe9tPH5U2la2pU7nbzsAFjRAOQyx/nitxXLMxClPeM5yyx+yNV+YqTVcXLMwEHU
rascBwx76ioRAuc6QOdRXHR2xJxkD1nAqC7HsxPt3ES+oOx+Q/nUutk8Wy7EftLmVvCOHT8yamsW
Wki2Uv/AC7mX+JlX8KzrStoTLf2K/s7FT4ySM340/yXcoNpJZo4I11NkqeuBnsXPIc/fWouzJYIp
dTaYojnH1lyB6hWkWVjuP8A26eqKLNLhxS47bkD+HA/CgVbVmwHu3x4s5H4VF3n/wCDxZINwSO/U
Tmlw07Mtxx1sx8Af50uidI4wPrN7qKkWVBy1H2AfzqImW+UfZb3ircQXM6t9g5HAHV/2pcsq6aXC
4pcGaXAspB4cKXD/PJPSx7BS4z/ADFe81FOFinjQO8zTuPvoFFondQOECdwoHAKOWBQKZF7x76Bv
TJ3iiENynf8jQHnad59xoXIb1fH3ULm+er3H5UB56O750DTfH0fnRbmm9buFVLk88bwqBvnb9/yq
oTzlu/8KlghnbvNVTTKe8+80LkzRD+nb0j8qLc0yt6R99EJrPeffQJk9599AZopKIKAoCgKAzQJq
HeKA1CgNX/mDQGfA+6inqhPZQsd0JoWKIDUuWO83PfS5Yvm3jS66pwtx30LKmG7l95qoXS3h86A0
t3j3UQaD6Xyoo6M+kflRLjo/E/Kijoh3n30C9EP/CaIOiHdRS6B3D3UQYHcKKXFELQJQPj51FSxj
8TRo+gWpZbCilxUS5QKpxUq0wKIKAoCiCiiiiiCgKKSgWgSiFoHRcxRU6dvrqKdiopQKFy4oFooo
QomtOYoCgKIKKKAooogoDFAUUUBQFEOj5iipxzNRTwKKdUC0UUC4qChW3IhoooFoFoEoXFEFAUWC
UBQkUBRS0QLzFFWgOPsqB4qXUoopcUkLikBRQZ1acxRRigKKWiEogoCgKKKBKFhmhYuKAoCgtjn7
KjSTTUCgUsooFpYKKsozqrIoEoCigUSS0CULigKAoFFAlAtEJRRQXV7PVUWElSVuKWC4qgAoHYor
MFVgUCUBQLQFAUCUQUUtAUCUBQLRBRVuPkv/nZRpNUDgKKKBcUC4oMo1WIFAUCUCigKAoENELRRQ
FAlAUCigKC3F9VfXRpOKgcKKWgBUDqSj//Z
"""
